[target.riscv32imac-unknown-none-elf]
# The line below is for USB communication
runner = "./espflash flash --before usb-reset --monitor"
# The line below is for UART communication
# runner = "./espflash flash --before no-reset --monitor"

[build]
target = "riscv32imac-unknown-none-elf"
rustflags = ["-C", "link-arg=-Tlinkall.x", "-C", "force-frame-pointers"]

[unstable]
build-std = ["alloc", "core"]
